title: MqttGateway
description: Mqtt Gateway
url: "https://mqttmagic.com/mqtt-gateway"
project: mqttgateway
markdown: kramdown
permalink: /:title
google_analytics: UA-
youtube: https://www.youtube.com/user/
github:
  repository_url: https://github.com/wizard-of-things/mqtt-gateway
  raw_content_url: https://raw.githubusercontent.com/wizard-of-things/mqtt-gateway/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "scripts", "firmware"]
include: ["_data"]
